# Generated by Django 5.1.3 on 2024-11-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
